fix src problem but now dosent import it with error :(
ImportError: attempted relative import with no known parent package

# Conflicts:
#	main.py
#	src/App.py
#	src/Gui/App.py
#	src/Gui/MainApp.py
#	src/find/Gui/App.py
#	src/find/Gui/MainApp.py
#	src/mainapp.py